kind: pipeline
type: docker
name: default

steps:
- name: build-linux
  image: thatcosmonaut/moonworks-build
  commands:
    - cmake -E make_directory ./build
    - cd ./build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/clang -S .. -B .
    - make
    - mv ./cramcli ./cramcli-linux-amd64

- name: build-windows
  image: thatcosmonaut/moonworks-build
  commands:
    - cmake -E make_directory ./windows-build
    - cd ./windows-build
    - mingw64-cmake -S .. -B .
    - make

- name: gitea_release
  image: plugins/gitea-release
  settings:
    base_url: https://gitea.moonside.games
    api_key:
      from_secret: gitea_token
    files:
      - ./build/cramcli-linux-amd64
      - ./windows-build/cramcli.exe
  when:
    event: tag
